### PR TITLE
Use isArray

### PR DESCRIPTION
**Pull request by josepjaume**
I've recently run into a bug in the newer versions of babel where `instanceof Array` was returning false. After [a bit of research](https://github.com/eslint/eslint/issues/7757), it turns out using `Array.isArray` is a much better alternative.

This replaces the usage of `array instanceof Array` with `Array.isArray(array)`

### CODE REVIEW

**Comment by Yimiprod** [comment]
Hello, is there any news about this pull request ? Do you know if it's going to be merged soon?

**Comment by benoitemile** [comment]
hi, any update on this ?

**Comment by benoitemile** [comment]
hi @arnaudlewis,
We really need this to be merged. We're struggling with this issue and can't upgrade our other dependencies just because of this, causing build errors.
Could you please give us an update ?

**Comment by Atinux** [comment]
Ping here from Nuxt.js author, people need this as it's breaking the server-side rendering part.

Current patch: https://github.com/prismicio/prismic-javascript/issues/77#issuecomment-473966443

**Comment by arnaudlewis** [comment]
Sorry for the delay, it's available in 2.0.2

**Pull request merged**
